add parameters and improve error handling
closes #3
closes #4
closes #6

diff --git a/bbsync b/bbsync
--- a/bbsync
+++ b/bbsync
@@ -2,20 +2,26 @@
 
 #{{{ parameter parsing
 shopt -s extglob
-verbose=0
+connectTimeout=0
 dryRun=0
+force=""
+maxTime=0
 minshow=0
-progress=1
 processes=1
+progress=1
 server=""
+verbose=0
 usage="Usage: $(basename "$0") [OPTIONS]
-  -d, --dry-run           perform a trial run with no changes made
-  --minshow NUM           minimum time in seconds to show actions
-  --no-progress           do not show progress during transfer
-  -p, --processes NUM     number of processes to use
-  --server URL            master server URL
-  -v, --verbose           output a diagnostic for every file that will be processed
-  -h, --help              display this help
+  --connect-timeout NUM     maximum time in seconds to allow connection attempts
+  -d, --dry-run             perform a trial run with no changes made
+  --force [push, pull]      ignore master/local state
+  --max-time NUM            maximum time in seconds to allow transfers
+  --minshow NUM             minimum time in seconds to show actions
+  --no-progress             do not show progress during transfer
+  -p, --processes NUM       number of processes to use
+  --server URL              master server URL
+  -v, --verbose             output a diagnostic for every file that will be processed
+  -h, --help                display this help
 "
 for (( i=1; i <= $#; i++ )); do
 	[ "${!i:0:1}" != "-" ] && { printf "$usage"; exit 2; }
@@ -23,8 +29,20 @@ for (( i=1; i <= $#; i++ )); do
 
 	#{{{ long parameters
 		case "${!i}" in
+			--connect-timeout)
+				i=$((i+1))
+				connectTimeout="${!i}"
+			;;
 			--dry-run)
 				dryRun=1
+			;;
+			--force)
+				i=$((i+1))
+				force="${!i}"
+			;;
+			--max-time)
+				i=$((i+1))
+				maxTime="${!i}"
 			;;
 			--minshow)
 				i=$((i+1))
@@ -78,9 +96,38 @@ done
 #}}}
 
 #{{{ parameter validation
+	#{{{ connect-timeout
+case "$connectTimeout" in
+	""|*[!0-9.]*)
+		printf "$usage" >&2
+		exit 2
+	;;
+esac
+	#}}}
+
+	#{{{ force
+case "$force" in
+	""|"push"|"pull") ;;
+	*)
+		printf "$usage" >&2
+		exit 2
+	;;
+esac
+	#}}}
+
+	#{{{ max-time
+case "$maxTime" in
+	""|*[!0-9]*)
+		printf "$usage" >&2
+		exit 2
+	;;
+esac
+[ $maxTime -ne 0 ] && maxTime=" --max-time $maxTime" || maxTime=
+	#}}}
+
 	#{{{ minshow
 case "$minshow" in
-	""|*[!0-9]*)
+	""|*[!0-9.]*)
 		printf "$usage" >&2
 		exit 2
 	;;
@@ -96,14 +143,19 @@ case "$processes" in
 esac
 	#}}}
 
-[ "$(curl --insecure --connect-timeout 5 --silent -o /dev/null --write-out "%{http_code}" "$server/bbsync")" = "200" ] || { printf "Unable to connect to server!\n" >&2; exit 1; }
+server="${server%/}"
+[ "$(curl --insecure --connect-timeout $((connectTimeout > 5 ? connectTimeout : 5)) --silent -o /dev/null --write-out "%{http_code}" "$server/bbsync")" = "200" ] || { printf "Unable to connect to server!\n" >&2; exit 1; }
+[ $connectTimeout -ne 0 ] && connectTimeout=" --connect-timeout $connectTimeout" || connectTimeout=
 #}}}
 
 #{{{ startup and safety checks
 printf "Note that symlinks will be created as normal files/folders if they do not already exist. Run \`find -L sync/* -mindepth 1 -xtype l\` to list any.\n" >&2
 cd -- "$(dirname "$0")/sync" || { printf "sync dir does not exist!" >&2; exit 1; }
 # abnormal exits cause this to not trigger if using -p
-{ [ -f ../skipdirs ] || [ -e ../actions ] || [ -e ../processes ]; } && { printf "FIFO(s) exist! Not running in case of mangled data or another process.\n" >&2; exit 1; }
+{ [ -f ../skipdirs ] || [ -e ../actions ] || [ -e ../processes ]; } && {
+	printf "FIFO(s) exist! Not running in case of mangled data or another process.\n" >&2
+	exit 1
+}
 [ -w .. ] || { printf "Cannot write to bbsync dir!\n" >&2; exit 1; }
 rm -f ../bbsync-list-master || { printf "Could not remove old bbsync-list-master!\n" >&2; exit 1; }
 rm -f ../bbsync-list || { printf "Could not remove old bbsync-list!\n" >&2; exit 1; }
@@ -135,9 +187,10 @@ abort() {
 	# suppressing stderr on kill because they may have exited already
 	if [ -n "$p_actions" ]; then
 		printf "\033[KAborting. . . \r"
-		kill -0 $p_actions 2>/dev/null && { printf "END\n" > ../actions & kill $p_actions 2>/dev/null; }
-		# TODO: kill curls, letting their restores trigger and subprocesses to exit
+		kill $p_actions 2>/dev/null && printf "END\n" > ../actions
 		[ "$(head -n 1 ../bbsync-list-last)" = "END" ] && rm ../bbsync-list-last
+		# TODO: kill curls, letting their restores trigger and subprocesses to exit
+		printf "\033[KAborting, waiting on $((started-done)) process(es). . . \r" >&2
 	elif [ -n "$p_master" ]; then
 		kill $p_master 2>/dev/null
 		rm ../bbsync-list ../bbsync-list-master ../skipdirs
@@ -150,7 +203,7 @@ trap "abort" SIGINT
 #}}}
 
 #{{{ generate bbsync-lists
-{ [ "$(curl --insecure --silent -o ../bbsync-list-master --write-out "%{http_code}" "$server/sync/bbsync-list")" = "200" ] || printf "FAILED\n" > ../bbsync-list-master; } &
+{ [ "$(curl$connectTimeout$maxTime --insecure --silent -o ../bbsync-list-master --write-out "%{http_code}" "$server/sync/bbsync-list")" = "200" ] || printf "FAILED\n" > ../bbsync-list-master; } &
 p_master=$!
 find -L . -mindepth 1 -type d -prune | LC_ALL=C sort > ../bbsync-list
 printf "END SYNC FOLDERS\n" >> ../bbsync-list
@@ -285,17 +338,17 @@ mkfifo ../actions; {
 			if [ "$file" != "END" ] && { [ "$fileMaster" = "END" ] || [ "$file" \< "$fileMaster" ]; }; then
 				# meta/data could have changed too, so not comparing using line
 				if [ "$lineLast" = "END" ] || [ "$file" != "${lineLast% * * * *}" ]; then
-					printf "%s0\n" "$line"
+					[ "$force" != "pull" ] && printf "%s0\n" "$line" || printf "%s5\n" "$line"
 				else
-					printf "%s5\n" "$line"
+					[ "$force" != "push" ] && printf "%s5\n" "$line" || printf "%s0\n" "$line"
 				fi
 				IFS= read -r line <&3
 			else
 				# meta/data could have changed too, so not comparing using line
 				if [ "$lineLast" = "END" ] || [ "$fileMaster" != "${lineLast% * * * *}" ]; then
-					printf "%s1\n" "$lineMaster"
+					[ "$force" != "push" ] && printf "%s1\n" "$lineMaster" || printf "%s4\n" "$lineMaster"
 				else
-					printf "%s4\n" "$lineMaster"
+					[ "$force" != "pull" ] && printf "%s4\n" "$lineMaster" || printf "%s1\n" "$lineMaster"
 				fi
 				IFS= read -r lineMaster <&4
 			fi
@@ -306,7 +359,6 @@ mkfifo ../actions; {
 			if [ "$line" != "$lineMaster" ]; then
 
 	#{{{ updated on one end
-
 		#{{{ variable prep
 				fileF="${line##* }"; line="${line% *}"
 				fileH="${line##* }"; line="${line% *}"
@@ -321,15 +373,21 @@ mkfifo ../actions; {
 				if [ "$fileH" = "$fileMasterH" ]; then
 
 		#{{{ only metadata changed
-					if [ $fileD -gt $fileMasterD ]; then
+					if [ "$force" = "push" ]; then
 						printf "%s %s %s %s %s2\n" "$file" "$fileP" "$fileD" "$fileH" "$fileF"
-					elif [ "$fileD" != "$fileMasterD" ]; then
+					elif [ "$force" = "pull" ]; then
 						printf "%s %s %s %s %s3\n" "$fileMaster" "$fileMasterP" "$fileMasterD" "$fileMasterH" "$fileMasterF"
 					else
-						if [ "$file $fileP $fileD $fileH $fileF" != "$lineLast" ]; then
+						if [ $fileD -gt $fileMasterD ]; then
 							printf "%s %s %s %s %s2\n" "$file" "$fileP" "$fileD" "$fileH" "$fileF"
-						else
+						elif [ "$fileD" != "$fileMasterD" ]; then
 							printf "%s %s %s %s %s3\n" "$fileMaster" "$fileMasterP" "$fileMasterD" "$fileMasterH" "$fileMasterF"
+						else
+							if [ "$file $fileP $fileD $fileH $fileF" != "$lineLast" ]; then
+								printf "%s %s %s %s %s2\n" "$file" "$fileP" "$fileD" "$fileH" "$fileF"
+							else
+								printf "%s %s %s %s %s3\n" "$fileMaster" "$fileMasterP" "$fileMasterD" "$fileMasterH" "$fileMasterF"
+							fi
 						fi
 					fi
 		#}}}
@@ -337,14 +395,20 @@ mkfifo ../actions; {
 				else
 
 		#{{{ modified
-					if [ "$fileD" -gt "$fileMasterD" ]; then
+					if [ "$force" = "push" ]; then
 						printf "%s %s %s %s %s0\n" "$file" "$fileP" "$fileD" "$fileH" "$fileF"
-					elif [ "$fileD" != "$fileMasterD" ]; then
+					elif [ "$force" = "pull" ]; then
 						printf "%s %s %s %s %s1\n" "$fileMaster" "$fileMasterP" "$fileMasterD" "$fileMasterH" "$fileMasterF"
 					else
-						done=$((done+1))
-						errors=$((errors+1))
-						printf "%s has been corrupted on one end! Mtimes are equal, size/hashes are not!\n" "$file" >> ../log
+						if [ "$fileD" -gt "$fileMasterD" ]; then
+							printf "%s %s %s %s %s0\n" "$file" "$fileP" "$fileD" "$fileH" "$fileF"
+						elif [ "$fileD" != "$fileMasterD" ]; then
+							printf "%s %s %s %s %s1\n" "$fileMaster" "$fileMasterP" "$fileMasterD" "$fileMasterH" "$fileMasterF"
+						else
+							done=$((done+1))
+							errors=$((errors+1))
+							printf "%s has been corrupted on one end! Mtimes are equal, size and/or hashes are not!\n" "$file" >> ../log
+						fi
 					fi
 		#}}}
 
@@ -418,18 +482,18 @@ if [ $total -ne 0 ]; then
 
 				#{{{ upload
 								if [ "$fileF" = "d" ]; then
-									IFS= read -r code < <(curl --insecure --silent -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "perms=$fileP" -F "mtime=$fileD" -F "dir=1" "$server/sync")
+									IFS= read -r code < <(curl$connectTimeout$maxTime --insecure --silent -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "perms=$fileP" -F "mtime=$fileD" -F "dir=1" "$server/sync")
 									printp $process "--> %s" "$name DONE (directory)" >&2
 								else
 									IFS= read -r code < <(
-										curl --insecure --progress-bar -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "perms=$fileP" -F "mtime=$fileD" -F "size=$(stat -c "%s" "$file")" -F "file=@$(realpath "$file")" "$server/sync" 2> >(
+										curl$connectTimeout$maxTime --insecure --progress-bar -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "perms=$fileP" -F "mtime=$fileD" -F "size=$(stat -c "%s" "$file")" -F "file=@$(realpath "$file")" "$server/sync" 2> >(
 											while IFS= read -r -d "%" progress; do
 												printp $process "--> %s" "$name #${progress#*#}%" >&2
 											done
 										)
 									)
 								fi
-								[ "$code" = "200" ] || error=1
+								[ "$code" = "200" ] || { error=1; printf "Failed to upload %s.\n" "$file" >> ../log; }
 				#}}}
 
 							;;
@@ -437,13 +501,13 @@ if [ $total -ne 0 ]; then
 
 				#{{{ download
 								if [ "$fileF" = "d" ]; then
-									mkdir -p "$file" 2>>../log || error=1
+									mkdir -p "$file" 2>>../log || { error=1; printf "Failed to create %s.\n" "$file" >> ../log; }
 									printp $process "<-- %s" "$name DONE (directory)" >&2
 								else
 									real="$(realpath "$file")"
 									if [ ! -e "$real" ] || mv -f "$real" "$real.bak-bbsync" 2>>../log; then
 										IFS= read -r code < <(
-											curl --insecure --progress-bar -o "$real" --write-out "%{http_code}" "$server/sync/$file" 2> >(
+											curl$connectTimeout$maxTime --insecure --progress-bar -o "$real" --write-out "%{http_code}" "$server/sync/$file" 2> >(
 												while IFS= read -r -d "%" progress; do
 													printp $process "<-- %s" "$name #${progress#*#}%" >&2
 												done
@@ -451,23 +515,25 @@ if [ $total -ne 0 ]; then
 										)
 										[ "$code" = "200" ] || {
 											error=1
-											mv -f "$real.bak-bbsync" "$real" 2>>../log
+											mv -f "$real.bak-bbsync" "$real" 2>/dev/null || rm "$real"
 											printf "Failed to download %s.\n" "$file" >> ../log
 										}
 									else
 										error=1
+										printf "Failed to back up %s.\n" "$file" >> ../log
 									fi
-									rm -rf "$real.bak-bbsync" 2>>../log
+									rm -rf "$real.bak-bbsync"
 								fi
-								chmod $fileP "$file"
-								touch -m -d "@$fileD" "$file"
+								{ chmod $fileP "$file" && touch -m -d "@$fileD" "$file"; } 2>>../log || {
+									error=1; printf "Failed to set local metadata of %s.\n" "$file" >> ../log
+								}
 				#}}}
 
 							;;
 							"2")
 
 				#{{{ change master metadata
-								curl --insecure --silent -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "perms=$fileP" -F "mtime=$fileD" "$server/sync" > >(
+								curl$connectTimeout$maxTime --insecure --silent -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "perms=$fileP" -F "mtime=$fileD" "$server/sync" > >(
 									IFS= read -r code
 									[ "$code" = "200" ] || { error=1; printf "Failed to set master metadata of %s.\n" "$file" >> ../log; }
 								)
@@ -478,8 +544,8 @@ if [ $total -ne 0 ]; then
 							"3")
 
 				#{{{ change local metadata
-								chmod $fileP "$file" && touch -m -d "@$fileD" "$file" || {
-									[ "$code" = "200" ] || { error=1; printf "Failed to set local metadata of %s.\n" "$file" >> ../log; }
+								{ chmod $fileP "$file" && touch -m -d "@$fileD" "$file"; } 2>>../log || {
+									error=1; printf "Failed to set local metadata of %s.\n" "$file" >> ../log
 								}
 				#}}}
 
@@ -487,9 +553,9 @@ if [ $total -ne 0 ]; then
 							"4")
 
 			#{{{ remove master
-								curl --insecure --silent -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "remove=1" "$server/sync" > >(
+								curl$connectTimeout$maxTime --insecure --silent -o >(cat >> ../log) --write-out "%{http_code}" -F "path=$file" -F "remove=1" "$server/sync" > >(
 									IFS= read -r code
-									[ "$code" = "200" ] || error=1
+									[ "$code" = "200" ] || { error=1; printf "Failed to remove master %s.\n" "$file" >> ../log; }
 								)
 								printp $process "--> %s" "$name DONE (remove)" >&2
 			#}}}
@@ -499,7 +565,7 @@ if [ $total -ne 0 ]; then
 
 			#{{{ remove local
 								if [ -e "$file" ]; then
-									rm -rf "$file" 2>>../log || error=1
+									rm -r "$file" 2>>../log || { error=1; printf "Failed to remove local %s.\n" "$file" >> ../log; }
 								fi
 								printp $process "<-- %s" "$name DONE (remove)" >&2
 			#}}}
@@ -526,39 +592,42 @@ if [ $total -ne 0 ]; then
 			printf "\033[KAborting, waiting on $((started-done)) process(es). . . \r" >&2
 		fi
 		IFS= read -r process <&4
+		if [ -n "$process" ]; then
 
 	#{{{ info variable updating
-		done=$((done+1))
-		if [ ${process##* } -eq 0 ]; then
-			process=${process% *}
-			case "${process#* }" in
-				"0")
-					pushed=$((pushed+1))
-				;;
-				"1")
-					pulled=$((pulled+1))
-				;;
-				"2")
-					mmaster=$((mmaster+1))
-				;;
-				"3")
-					mlocal=$((mlocal+1))
-				;;
-				"4")
-					rmaster=$((rmaster+1))
-				;;
-				"5")
-					rlocal=$((rlocal+1))
-				;;
-			esac
-		else
-			errors=$((errors+1))
-		fi
+			done=$((done+1))
+			if [ ${process##* } -eq 0 ]; then
+				process=${process% *}
+				case "${process#* }" in
+					"0")
+						pushed=$((pushed+1))
+					;;
+					"1")
+						pulled=$((pulled+1))
+					;;
+					"2")
+						mmaster=$((mmaster+1))
+					;;
+					"3")
+						mlocal=$((mlocal+1))
+					;;
+					"4")
+						rmaster=$((rmaster+1))
+					;;
+					"5")
+						rlocal=$((rlocal+1))
+					;;
+				esac
+			else
+				errors=$((errors+1))
+			fi
 	#}}}
 
-		export process=${process%% *}
+			export process=${process%% *}
+		fi
 		{ [ $aborting -ne 0 ] || [ "$line" = "END" ]; } && [ $done -eq $started ] && break
-	done 3<../actions 4< <(tail -f ../processes)
+	# this trap seems to affect the entire loop, which is actually very handy
+	done 3<../actions 4< <(trap "" SIGINT; tail -f ../processes)
 fi
 #}}}
 
